export const READ_CARD_TYPES_SUCCESSFUL = 'READ_CARD_TYPES_SUCCESSFUL';
export const READ_CARD_TYPES_PENDING = 'READ_CARD_TYPES_PENDING';
export const READ_CARD_TYPES_FAILURE = 'READ_CARD_TYPES_FAILURE';
