export const READ_CARD_TYPES_SUCCESSFUL = 'READ_CARD_TYPES_SUCCESSFUL';
export const READ_CARD_TYPES_PENDING = 'READ_CARD_TYPES_PENDING';
export const READ_CARD_TYPES_FAILURE = 'READ_CARD_TYPES_FAILURE';

export const READ_LOAN_TYPES_SUCCESS = 'READ_LOAN_TYPES_SUCCESS';
export const READ_LOAN_TYPES_PENDING = 'READ_LOAN_TYPES_PENDING';
export const READ_LOAN_TYPES_FAILURE = 'READ_LOAN_TYPES_FAILURE';

export const CREATE_CARD_PENDING = 'CREATE_CARD_PENDING';
export const CREATE_CARD_SUCCESS = 'CREATE_CARD_SUCCESS';
export const CREATE_CARD_FAILURE = 'CREATE_CARD_FAILURE';

export const CREATE_LOAN_PENDING = 'CREATE_LOAN_PENDING';
export const CREATE_LOAN_SUCCESS = 'CREATE_LOAN_SUCCESS';
export const CREATE_LOAN_FAILURE = 'CREATE_LOAN_FAILURE';