export const READ_CARD_TYPES_SUCCESFUL = 'READ_CARD_TYPES_SUCCESFUL';
export const READ_CARD_TYPES_PENDING = 'READ_CARD_TYPES_PENDING';
export const READ_CARD_TYPES_FAILURE = 'READ_CARD_TYPES_FAILURE';
